/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Maicol Velasquez
 */
public class JNomina extends javax.swing.JFrame {

    /**
     * Creates new form JNomina
     */
    public JNomina() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonEditarD2 = new javax.swing.JButton();
        jButtonEditarD3 = new javax.swing.JButton();
        jButtonEditarD4 = new javax.swing.JButton();
        jButtonEditarD5 = new javax.swing.JButton();
        jLabelfondomain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(171, 210, 248));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/icoNomi/INomina2.png"))); // NOI18N
        jLabel1.setText("Nomina");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jButtonEditarD2.setBackground(new java.awt.Color(102, 153, 255));
        jButtonEditarD2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonEditarD2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/verNo.png"))); // NOI18N
        jButtonEditarD2.setText("Ver Nomina");
        jButtonEditarD2.setActionCommand("Editar Datos   ");
        jButtonEditarD2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonEditarD2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonEditarD2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/verNo2.png"))); // NOI18N
        jPanel2.add(jButtonEditarD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 250, 60));

        jButtonEditarD3.setBackground(new java.awt.Color(102, 153, 255));
        jButtonEditarD3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonEditarD3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarD3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/agregar.png"))); // NOI18N
        jButtonEditarD3.setText("Crear Contrato");
        jButtonEditarD3.setActionCommand("Editar Datos   ");
        jButtonEditarD3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonEditarD3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonEditarD3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/agregar2.png"))); // NOI18N
        jPanel2.add(jButtonEditarD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 250, 60));

        jButtonEditarD4.setBackground(new java.awt.Color(102, 153, 255));
        jButtonEditarD4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonEditarD4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarD4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/eliminar.png"))); // NOI18N
        jButtonEditarD4.setText("Eliminar Contrato");
        jButtonEditarD4.setActionCommand("Editar Datos   ");
        jButtonEditarD4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonEditarD4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonEditarD4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/agregar2.png"))); // NOI18N
        jPanel2.add(jButtonEditarD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 260, 60));

        jButtonEditarD5.setBackground(new java.awt.Color(102, 153, 255));
        jButtonEditarD5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButtonEditarD5.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarD5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/sacarNo.png"))); // NOI18N
        jButtonEditarD5.setText("Hacer Nomina");
        jButtonEditarD5.setActionCommand("Editar Datos   ");
        jButtonEditarD5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonEditarD5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonEditarD5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/sacarNo2.png"))); // NOI18N
        jPanel2.add(jButtonEditarD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 250, 60));

        jLabelfondomain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/imagenes/fondo.jpg"))); // NOI18N
        jPanel2.add(jLabelfondomain, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 290, 1020));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1711, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarD2;
    private javax.swing.JButton jButtonEditarD3;
    private javax.swing.JButton jButtonEditarD4;
    private javax.swing.JButton jButtonEditarD5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelfondomain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
